<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Gaji;
use App\Models\MasterPotongan;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GajiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Tentukan ID karyawan yang akan dibuatkan data gaji
        $karyawanId = 7;
        $user = User::find($karyawanId);

        // Hentikan seeder jika karyawan tidak ditemukan
        if (!$user) {
            $this->command->error("Karyawan dengan ID {$karyawanId} tidak ditemukan.");
            return;
        }

        // 2. Ambil beberapa jenis potongan dari master untuk dijadikan sampel
        $masterPotonganSampel = MasterPotongan::whereIn('nama_potongan', [
            'Koperasi', 'Bank BRI', 'Zakat', 'Infaq'
        ])->get();

        // Hentikan jika tidak ada master potongan
        if ($masterPotonganSampel->isEmpty()) {
            $this->command->error("Master potongan tidak ditemukan. Pastikan Anda sudah menjalankan MasterPotonganSeeder.");
            return;
        }

        // 3. Loop untuk membuat 3 data gaji (3 bulan terakhir)
        for ($i = 0; $i < 3; $i++) {
            $tanggal = Carbon::now()->subMonths($i);
            $bulan = $tanggal->month;
            $tahun = $tanggal->year;

            // Gunakan transaction untuk menjaga konsistensi data
            DB::transaction(function () use ($user, $bulan, $tahun, $masterPotonganSampel) {
                
                $gajiPokok = 5000000;
                $totalPotongan = 0;
                $detailPotonganToSave = [];

                // Buat 2-3 potongan acak untuk setiap slip gaji
                $sampelUntukBulanIni = $masterPotonganSampel->random(rand(2, 3));

                foreach ($sampelUntukBulanIni as $potongan) {
                    $jumlahPotongan = rand(50, 200) * 1000; // Contoh jumlah acak (50rb - 200rb)
                    $totalPotongan += $jumlahPotongan;
                    $detailPotonganToSave[] = [
                        'master_potongan_id' => $potongan->id,
                        'jumlah' => $jumlahPotongan,
                    ];
                }

                $gajiDiterima = $gajiPokok - $totalPotongan;

                // Buat record utama di tabel 'gaji'
                $gaji = Gaji::create([
                    'user_id' => $user->id,
                    'bulan' => $bulan,
                    'tahun' => $tahun,
                    'gaji_pokok' => $gajiPokok,
                    'total_potongan' => $totalPotongan,
                    'gaji_diterima' => $gajiDiterima,
                    'file_slip' => null, // Sesuai permintaan Anda, file dikosongkan
                    'keterangan' => 'Generated by Seeder',
                ]);

                // Buat record di tabel 'detail_potongan'
                $gaji->detailPotongan()->createMany($detailPotonganToSave);
            });
        }
        
        $this->command->info("Seeder gaji untuk {$user->nama_lengkap} berhasil dijalankan.");
    }
}